export { default as BasicInformationForm } from './BasicInformationForm.vue'
export { default as BudgetStrategyForm } from './BudgetStrategyForm.vue'
export { default as FinancialGoalsForm } from './FinancialGoalsForm.vue'
export { default as Form } from './Form.vue'
export { default as IncomesForm } from './IncomesForm.vue'
export { default as LoginForm } from './LoginForm.vue'
