export type TextSize = 'xs' | 'sm' | 'base' | 'lg' | 'xl'
export type TextWeight = 'light' | 'normal' | 'medium' | 'semibold' | 'bold'
export type TextColor =
  | 'primary'
  | 'secondary'
  | 'muted'
  | 'accent'
  | 'success'
  | 'warning'
  | 'error'
  | 'white'
  | 'black'
  | 'inherit'
export type TextAlign = 'left' | 'center' | 'right' | 'justify'
